export {
  $duration,
  $currentTime,
  setCurrentTimeEvent,
  $pause,
  pauseEvent,
  playEvent,
  clearDurationEvent,
  durationSetEvent,
  setActiveTrackEvent,
  $activeTrack,
  setVolumeActionEvent,
  $volume,
  $nextTrack,
  $prevTrack,
  playPrevTrackEvent,
  playNextTrackEvent,
  trackEndedEvent,
  tracksQueueSetNextEvent,
  $isActiveTrackInTracksQueue,
  $activeTrackExist,
  tracksQueueSetQueueEvent,
  currentTimeTickEvent,
  togglePlayerEvent,
} from './player';

export { useIsCurrentTrack, } from './hooks';
